# Datos de conexion a Neon (PostgreSQL en la nube).
# En el dashboard de Neon, copia los datos de tu "Connection string":
#   postgres://USUARIO:CONTRASENA@HOST/NOMBRE_BD?sslmode=require
# y repatirlos aqui\u00ad:

###
db.url= jdbc:postgresql://neondb_owner:npg_Uqt2iJxTzl6h@ep-flat-firefly-b4vqpx19-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
db.user=neondb_owner
db.password=npg_Uqt2iJxTzl6h
